name: cash-flow-transaction-service

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: cash-flow-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=cash-flow-transaction-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "admin",
          "-d",
          "cash-flow-transaction-service",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cash-flow-network

volumes:
  postgres-data:

networks:
  cash-flow-network:
    driver: bridge
